import { getLocale, t as translate, type Locale, type TFunc } from "@/lib/i18n"
import {
  money as formatMoney,
  monthsFull,
  nightsLabel,
  shortDate,
  weekdaysShort,
} from "@/lib/format"
import type { CalendarLabels } from "./types"


export function groupThousands(n: number): string {
  const s = Math.round(Math.abs(n)).toString()
  return (n < 0 ? "-" : "") + s.replace(/\B(?=(\d{3})+(?!\d))/g, " ")
}

function build(t: TFunc): CalendarLabels {
  return {
    weekdaysShort: [...weekdaysShort()],
    months: [...monthsFull()],
    formatDay: (iso) => shortDate(iso),
    nights: (n) => nightsLabel(n),
    money: (amount) => formatMoney(amount),
    statusText: {
      booked: t("calendar.status.booked"),
      checked_in: t("calendar.status.checkedIn"),
      checked_out: t("calendar.status.checkedOut"),
      cancelled: t("calendar.status.cancelled"),
      blocked: t("calendar.status.blocked"),
    },
    blockKindText: {
      maintenance: t("blockKind.maintenance"),
      cleaning: t("blockKind.cleaning"),
      hold: t("blockKind.hold"),
      other: t("blockKind.otherReason"),
    },
    checkInTime: "14:00",
    checkOutTime: "12:00",
    nightsWord: t("units.nightWord"),
    guest: t("common.guest"),
    phone: t("common.phone"),
    stay: t("calendar.stayField"),
    payment: t("calendar.paymentField"),
    today: t("common.today"),
    noRoomsTitle: t("calendar.noRoomsTitle"),
    noRoomsHint: t("calendar.noRoomsHint"),
    newBooking: t("calendar.newBooking"),
    checkIn: t("calendar.checkedInAction"),
    checkOut: t("calendar.checkedOutAction"),
    cancel: t("calendar.cancelBooking"),
    guestName: t("calendar.guestName"),
    guestPhone: t("common.phone"),
    room: t("common.room"),
    arrival: t("stay.checkIn"),
    departure: t("stay.checkOut"),
    save: t("common.save"),
    close: t("common.close"),
    paid: t("payment.paid"),
    remaining: t("payment.remaining"),
    conflict: t("calendar.conflict"),

    edit: t("common.edit"),
    discard: t("common.cancel"),
    confirmed: t("calendar.confirmed"),
    notConfirmed: t("calendar.notConfirmed"),
    history: t("calendar.history"),
    historyCreated: t("calendar.activity.created"),
    historyCheckedIn: t("calendar.activity.checkedIn"),
    historyCheckedOut: t("calendar.activity.checkedOut"),
    actions: t("common.actions"),
    total: t("common.total"),
    nightlyRate: t("units.oneNight"),
    amount: t("common.amount"),
    lockedHint: t("calendar.lockedHint"),
    noChanges: t("calendar.noChanges"),

    rooms: t("common.rooms"),
    roomsSelected: (n) =>
      n === 0 ? t("calendar.roomsNotSelected") : t("calendar.roomsSelected", { count: n }),
    roomSearch: t("calendar.roomSearch"),
    roomsEmpty: t("calendar.roomsEmpty"),
    roomsFree: (n) => (n === 0 ? t("calendar.roomsNoFree") : t("calendar.roomsFree", { count: n })),
    roomsOnlyFree: t("calendar.roomsOnlyFree"),
    roomsAll: t("common.all"),
    roomsNone: t("common.cancelShort"),
    roomsClear: t("calendar.roomsClear"),
    roomsPickHint: t("calendar.roomsPickHint"),
    capacityWord: (n) => t("calendar.capacityWord", { count: n }),
    busy: t("calendar.busy"),
    selectedBusy: t("calendar.selectedBusy"),
    pastStart: t("calendar.pastStart"),
    needGuestName: t("calendar.needGuestName"),
    needGuestPhone: t("calendar.needGuestPhone"),
    needCompanionName: t("calendar.needCompanionName"),
    needRoom: t("calendar.needRoom"),
    summary: t("calendar.summary"),
    quickNights: t("calendar.quickNights"),
    prepayment: t("calendar.prepayment"),
    paymentUnpaid: t("payment.unpaid"),
    paymentPartial: t("payment.partial"),
    paymentFull: t("payment.full"),
    prepaymentTooBig: t("calendar.prepaymentTooBig"),
    create: t("calendar.create"),
    groupHint: (n) => t("calendar.groupHint", { count: n }),

    modeBooking: t("calendar.newBooking"),
    modeCorporate: t("calendar.corporate"),
    modeBlock: t("calendar.blockRoom"),
    blockTitle: t("calendar.blockRoom"),
    blockReason: t("common.reason"),
    blockReasonHint: t("calendar.blockReasonHint"),
    blockKind: t("common.type"),
    createBlock: t("calendar.blockRoom"),
    blockHint: t("calendar.blockHint"),

    companions: t("calendar.companions"),
    addGuest: t("calendar.addGuest"),
    removeGuest: t("common.delete"),
    primaryGuest: t("calendar.primaryGuest"),
    makePrimary: t("calendar.makePrimary"),
    document: t("common.document"),
    docNumber: t("docs.series"),
    docTypeNone: t("common.notSelected"),
    docTypeText: {
      passport: t("docs.passport"),
      id_card: t("docs.idCard"),
      birth_certificate: t("docs.birthCertificate"),
      driver_license: t("docs.driverLicense"),
      other: t("common.otherOption"),
    },
    note: t("common.note"),
    notePlaceholder: t("calendar.notePlaceholder"),
    capacityOver: (guests, capacity) => t("calendar.capacityOver", { guests, capacity }),
    guestsWord: (n) => t("calendar.guestsWord", { count: n }),

    rateNotSet: t("calendar.rateNotSet"),
    rateNotSetError: t("calendar.rateNotSetError"),
    totalBelowPaid: t("calendar.totalBelowPaid"),

    extraGuestRate: t("units.perNight"),
    extraGuests: t("calendar.extraGuests"),
    extraGuestsBreakdown: (guests, nights) =>
      t("calendar.extraGuestsBreakdown", {
        guests: t("calendar.guestsWord", { count: guests }),
        nights: nightsLabel(nights),
      }),
    openChat: t("nav.chat"),
    duplicate: t("common.copy"),
    extendStay: t("calendar.extendStay"),
    guestQr: t("calendar.guestQr"),
    unblock: t("common.open"),

    split: t("calendar.split"),
    splitTitle: t("calendar.splitTitle"),
    splitHint: t("calendar.splitHint"),
    splitDate: t("calendar.splitDate"),
    splitRoom: t("calendar.splitRoom"),
    splitFirst: t("calendar.splitFirst"),
    splitSecond: t("calendar.splitSecond"),
    splitBusy: t("calendar.splitBusy"),
    splitTooShort: t("calendar.splitTooShort"),
    splitLinked: t("calendar.splitLinked"),
    confirmSplit: t("calendar.confirmSplit"),

    invoice: t("calendar.invoice"),
    invoiceTitle: t("calendar.invoiceTitle"),
    invoiceNumber: t("calendar.invoiceNumber"),
    invoiceIssue: t("calendar.invoiceIssue"),
    invoicePrint: t("calendar.invoicePrint"),
    invoiceExcel: t("calendar.invoiceExcel"),
    invoiceStale: t("calendar.invoiceStale"),

    paymentHistory: t("calendar.paymentHistory"),
    receivePayment: t("calendar.receivePayment"),
    paymentNotePlaceholder: t("services.noteField"),
    paymentMethodText: {
      cash: t("payment.cash"),
      card: t("payment.card"),
      transfer: t("payment.transfer"),
      adjustment: t("payment.manual"),
    },
    voidPayment: t("payment.refund"),
    voidReasonPlaceholder: t("calendar.voidReasonPlaceholder"),
    voidCashReturned: t("calendar.voidCashReturned"),
    voidCashKept: t("calendar.voidCashKept"),
    voided: t("calendar.status.cancelled"),
    paymentOverRemaining: t("calendar.paymentOverRemaining"),
    paidReadOnlyHint: t("calendar.paidReadOnlyHint"),
    confirm: t("common.confirm"),

    activityText: {
      "booking.created": t("calendar.activity.created"),
      "booking.updated": t("calendar.activity.updated"),
      "booking.checked_in": t("calendar.activity.checkedIn"),
      "booking.checked_out": t("calendar.activity.checkedOut"),
      "booking.cancelled": t("calendar.activity.cancelled"),
      "booking.guest_added": t("calendar.activity.guestAdded"),
      "booking.guest_removed": t("calendar.activity.guestRemoved"),
      "booking.primary_changed": t("calendar.activity.primaryChanged"),
      "payment.recorded": t("calendar.activity.paymentRecorded"),
      "payment.voided": t("calendar.activity.paymentVoided"),
      "payment.adjusted": t("calendar.activity.paymentAdjusted"),
      "booking.split": t("calendar.activity.split"),
      "invoice.issued": t("calendar.activity.invoiceIssued"),
    },
    activityFallback: t("common.action"),
    activityFieldText: {
      room: t("common.room"),
      checkIn: t("stay.checkIn"),
      checkOut: t("stay.checkOut"),
      totalAmount: t("common.amount"),
      paidAmount: t("payment.paid"),
      guestName: t("common.guest"),
    },

    organization: t("calendar.organization"),
    corporateTitle: t("calendar.corporateBooking"),
    organizationPick: t("calendar.organizationPick"),
    organizationSearch: t("calendar.organizationSearch"),
    organizationEmpty: t("calendar.organizationEmpty"),
    orgRef: t("calendar.orgRef"),
    orgRefHint: t("calendar.orgRefHint"),
    orgDiscount: (percent) => t("calendar.orgDiscount", { percent }),
    orgBalance: t("calendar.orgBalance"),
    orgCreditLimit: t("calendar.orgCreditLimit"),
    orgOverLimit: (over) => t("calendar.orgOverLimit", { amount: formatMoney(over) }),
    corporateDiscountLine: t("calendar.corporateDiscount"),
    corporateBilling: t("calendar.corporateBilling"),
    corporateBillingHint: t("calendar.corporateBillingHint"),
    corporateBooking: t("calendar.corporateBooking"),
    corporateNoCash: t("calendar.corporateNoCash"),
    rooming: t("calendar.rooming"),
    roomingHint: t("calendar.roomingHint"),
    roomingPaste: t("calendar.roomingPaste"),
    roomingPasteHint: t("calendar.roomingPasteHint"),
    roomingApply: t("calendar.rooming"),
    roomingRoomEmpty: t("calendar.roomingRoomEmpty"),
    needOrganization: t("calendar.organizationPick"),
    needRoomingName: t("calendar.needRoomingName"),

    debtOnCheckOut: (remaining) => t("calendar.debtOnCheckOut", { amount: formatMoney(remaining) }),
    checkOutAnyway: t("calendar.checkOutAnyway"),
    cancelPaidWarning: (paid) => t("calendar.cancelPaidWarning", { amount: formatMoney(paid) }),
    cancelAnyway: t("calendar.cancelAnyway"),
    earlyCheckInWarning: (date) => t("calendar.earlyCheckInWarning", { date }),
    checkInAnyway: t("calendar.checkInAnyway"),
    back: t("common.back"),
  }
}

let cached: { locale: Locale; labels: CalendarLabels } | null = null

export function calendarLabels(): CalendarLabels {
  const locale = getLocale()
  if (!cached || cached.locale !== locale) cached = { locale, labels: build(translate) }
  return cached.labels
}

export function resolveLabels(partial?: Partial<CalendarLabels>): CalendarLabels {
  const base = calendarLabels()
  return partial ? { ...base, ...partial } : base
}
