import type { CalendarLabels } from "./types"


export function groupThousands(n: number): string {
  const s = Math.round(Math.abs(n)).toString()
  return (n < 0 ? "-" : "") + s.replace(/\B(?=(\d{3})+(?!\d))/g, " ")
}

export const defaultLabels: CalendarLabels = {
  weekdaysShort: ["Ya", "Du", "Se", "Ch", "Pa", "Ju", "Sh"],
  months: [
    "yanvar", "fevral", "mart", "aprel", "may", "iyun",
    "iyul", "avgust", "sentabr", "oktabr", "noyabr", "dekabr",
  ],
  nights: (n) => `${n} kecha`,
  money: (amount) => `${groupThousands(amount)} so'm`,
  statusText: {
    booked: "Bron qilingan",
    checked_in: "Joylashgan",
    checked_out: "Chiqib ketgan",
    cancelled: "Bekor qilingan",
    blocked: "Yopilgan",
  },
  blockKindText: {
    maintenance: "Ta'mir",
    cleaning: "Chuqur tozalash",
    hold: "Ushlab turilgan",
    other: "Boshqa sabab",
  },
  checkInTime: "14:00",
  checkOutTime: "12:00",
  nightsWord: "kecha",
  guest: "Mehmon",
  phone: "Telefon",
  stay: "Muddat",
  payment: "To'lov",
  today: "Bugun",
  noRoomsTitle: "Xona yo'q",
  noRoomsHint: "Bu mehmonxona uchun hali xona qo'shilmagan.",
  newBooking: "Yangi bron",
  checkIn: "Kirdi",
  checkOut: "Chiqdi",
  cancel: "Bronni bekor qilish",
  guestName: "Mehmon ismi",
  guestPhone: "Telefon",
  room: "Xona",
  arrival: "Kirish",
  departure: "Chiqish",
  save: "Saqlash",
  close: "Yopish",
  paid: "To'langan",
  remaining: "Qoldi",
  conflict: "Bu xona tanlangan sanalarda band",

  edit: "Tahrirlash",
  discard: "Bekor qilish",
  confirmed: "Tasdiqlagan",
  notConfirmed: "Tasdiqlanmagan",
  history: "Tarix",
  historyCreated: "Bron ochildi",
  historyCheckedIn: "Mehmon kirdi",
  historyCheckedOut: "Mehmon chiqdi",
  actions: "Harakatlar",
  total: "Jami",
  nightlyRate: "Bir kecha",
  amount: "Summa",
  lockedHint: "Mehmon kirgan — xona va kirish sanasi o'zgarmaydi, faqat chiqish uzayadi",
  noChanges: "O'zgarish kiritilmadi",

  rooms: "Xonalar",
  roomsSelected: (n) => (n === 0 ? "Xona tanlanmagan" : `${n} ta xona tanlandi`),
  roomSearch: "Xona raqami yoki turi",
  roomsEmpty: "Mos xona topilmadi",
  roomsFree: (n) => (n === 0 ? "bo'sh xona yo'q" : `${n} bo'sh`),
  roomsOnlyFree: "Bo'shlari",
  roomsAll: "Hammasi",
  roomsNone: "Bekor",
  roomsClear: "Tozalash",
  roomsPickHint: "Bosib turib sudrasangiz bir nechtasi, Shift bilan bossangiz oralig'i tanlanadi",
  capacityWord: (n) => `${n} o'rin`,
  busy: "Band",
  selectedBusy: "Tanlangan xonalardan biri bu sanalarda band",
  pastStart: "O'tgan kunga bron ochib bo'lmaydi",
  needGuestName: "Mehmon ismini kiriting",
  needGuestPhone: "Telefon raqamini kiriting",
  needCompanionName: "Hamroh mehmonning ismini kiriting",
  needRoom: "Kamida bitta xona tanlang",
  summary: "Xulosa",
  quickNights: "Tez tanlash",
  prepayment: "Oldindan to'lov",
  paymentUnpaid: "To'lanmagan",
  paymentPartial: "Qisman",
  paymentFull: "To'liq",
  prepaymentTooBig: "Avans jami summadan oshmasligi kerak",
  create: "Bron yaratish",
  groupHint: (n) => `${n} ta xona bitta amalda ochiladi — bittasi band bo'lsa hech biri yaratilmaydi`,

  modeBooking: "Yangi bron",
  modeBlock: "Xonani yopish",
  blockTitle: "Xonani yopish",
  blockReason: "Sabab",
  blockReasonHint: "Ixtiyoriy — masalan “kondisioner almashtiriladi”",
  blockKind: "Turi",
  createBlock: "Xonani yopish",
  blockHint: "Bu kunlarda xonaga bron qo'yib bo'lmaydi. Mehmon, pul va QR yo'q.",

  companions: "Hamroh mehmonlar",
  addGuest: "Mehmon qo'shish",
  removeGuest: "O'chirish",
  primaryGuest: "Asosiy",
  makePrimary: "Asosiy qilish",
  document: "Hujjat",
  docNumber: "Seriya va raqam",
  docTypeText: {
    passport: "Pasport",
    id_card: "ID karta",
    birth_certificate: "Tug'ilganlik guvohnomasi",
    driver_license: "Haydovchilik guvohnomasi",
    other: "Boshqa",
  },
  note: "Eslatma",
  notePlaceholder: "Masalan: kech keladi, beshik kerak",
  capacityOver: (guests, capacity) =>
    `${guests} mehmon — xona sig'imi ${capacity}. Qo'shimcha joy kerak bo'lishi mumkin.`,
  guestsWord: (n) => `${n} mehmon`,

  extraGuestCharge: "To'lovli",
  extraGuestRate: "Qo'shimcha o'rin · 1 kecha",
  extraGuests: "Qo'shimcha o'rin",
  extraGuestsBreakdown: (guests, nights) => `${guests} mehmon × ${nights} kecha`,
  extraGuestRateHint: "Narx kiritilmagan — qo'shimcha to'lov hisoblanmaydi",
  openChat: "Suhbat",
  duplicate: "Nusxalash",
  extendStay: "Uzaytirish",
  guestQr: "Mehmon QR",
  unblock: "Ochish",

  paymentHistory: "To'lovlar",
  receivePayment: "To'lov qabul qilish",
  paymentNotePlaceholder: "Izoh (ixtiyoriy)",
  paymentMethodText: {
    cash: "Naqd",
    card: "Karta",
    transfer: "O'tkazma",
    adjustment: "Qo'lda tuzatish",
  },
  voidPayment: "Storno",
  voidReasonPlaceholder: "Sabab (majburiy)",
  voided: "Bekor qilingan",
  paymentOverRemaining: "To'lov qoldiqdan oshmasligi kerak",
  paidReadOnlyHint: "To'langan summa faqat to'lov qabul qilish orqali o'zgaradi",
  confirm: "Tasdiqlash",

  activityText: {
    "booking.created": "Bron ochildi",
    "booking.updated": "Bron o'zgartirildi",
    "booking.checked_in": "Mehmon kirdi",
    "booking.checked_out": "Mehmon chiqdi",
    "booking.cancelled": "Bron bekor qilindi",
    "booking.guest_added": "Mehmon qo'shildi",
    "booking.guest_removed": "Mehmon o'chirildi",
    "booking.primary_changed": "Asosiy mehmon almashdi",
    "payment.recorded": "To'lov qabul qilindi",
    "payment.voided": "To'lov storno qilindi",
  },
  activityFallback: "Amal",
  activityFieldText: {
    room: "Xona",
    checkIn: "Kirish",
    checkOut: "Chiqish",
    totalAmount: "Summa",
    paidAmount: "To'langan",
    guestName: "Mehmon",
  },

  debtOnCheckOut: (remaining) =>
    `Qoldiq ${groupThousands(remaining)} so'm — mehmon hali to'lamagan.`,
  checkOutAnyway: "Qarz bilan chiqarish",
  cancelPaidWarning: (paid) =>
    `Bu bronda ${groupThousands(paid)} so'm to'lov qabul qilingan — bekor qilishda pul mehmonga qaytarilishi kerak.`,
  cancelAnyway: "Baribir bekor qilish",
  earlyCheckInWarning: (date) => `Bron ${date}da boshlanadi — mehmon bugun kiritilsinmi?`,
  checkInAnyway: "Bugun kiritish",
  back: "Ortga",
}

/** Prop bilan kelgan qisman override'ni default ustiga qo'yadi. */
export function resolveLabels(partial?: Partial<CalendarLabels>): CalendarLabels {
  return partial ? { ...defaultLabels, ...partial } : defaultLabels
}
